### ISSUE TITLE
"Invalid octal literal"

### ISSUE THREAD

**Issue by whisller** [Fale/isbn#10]
Hey,
today I wanted to add your library to my project, and php complained with an error message 
"Invalid octal literal - won't be reported by PHP but will work incorrectly".

It is inside of file `vendor/fale/isbn/src/Isbn/Hyphens.php` lines e.g. 144, 173, 191 etc. Everywhere where you did convertion to octals.

Some links:
- http://stackoverflow.com/questions/14981133/why-in-08-09-my-php-code-doesnt-work
- http://www.serverphorums.com/read.php?7,1106103

**Comment by Fale** [comment]
They are not octals, they are int. Which version of PHP are you using? Which Operative System and/or distribution?

**Comment by dwightwatson** [comment]
It looks as though PHP 7 will now interpret any integer that begins with a `0` as an octal ([see this reference of changes in PHP 7](https://github.com/tpunt/PHP7-Reference#error-on-invalid-octal-literals)).

The integers that begin with `0` in `Hyphens.php` simply need to have that zero removed and the code should continue to function. Happy to make a pull request that fixes this if you're interested @Fale.

Also it might be worthwhile adding PHP 7 as a platform on Travis CI (as an allowed failure) to facilitate in getting this package up to scratch for the new release.

**Comment by lasselehtinen** [comment]
I pumped in to the same issue. I have created a PR for this.

https://github.com/Fale/isbn/pull/12

**Comment by Fale** [comment]
Thanks for the bug and thanks to @lasselehtinen for the patch that has just been merged!

**Comment by dwightwatson** [comment]
Would you be able to tag a new release for the two recently merged PRs? 

Not sure if you're following semantic versioning or not, but as the exceptions PR is a breaking change you might consider bumping to 3.0.0.

**Comment by Fale** [comment]
Thanks for remembering me. Just done it :)

**Comment by dwightwatson** [comment]
Awesome, thanks so much!
