### ISSUE TITLE
Some invalid returned ISBNS

### ISSUE THREAD

**Issue by lJakel** [Fale/isbn#11]
Hello, while running some tests.

9781046230927

Comes back incorrectly formatted. It should be 
978-1-04-623092-7

But comes back as
978-1-04623092-7

Same pattern with
9781085490801

Not too sure why.

**Comment by bbtgp** [comment]
Its an octal issue. In hyphens.php Remove the leading 0's in front of all the numbers his code and it will fix the issue. Adding zeros makes it look pretty but php will not interpret it the way you intend.

**Comment by lJakel** [comment]
Yep, that works perfectly! Thanks!

**Comment by Fale** [comment]
Reopened with no particular explanation, re-closing it.
