### ISSUE TITLE
Hyphenation fails with 9783035503661 

### ISSUE THREAD

**Issue by karstenbruch** [Fale/isbn#14]
Hyphenation fails with 9783035503661 

result:
978-3-03-550366-1

should be:
978-3-0355-0366-1

**Comment by Fale** [comment]
Thanks!
Now is returning 978-3-03-550366-1 which I think is the correct one. Is it?

**Comment by karstenbruch** [comment]
it should return 978-3-0355-0366-1
so, no still wrong.

**Comment by Fale** [comment]
Thanks a lot for pointing it out!
Should be fixed now.
For some reason it was a fairly big error (int comparison as if they were strings) but in many cases the result was the same.

If you confirm the fix I'll cut a minor release
