### ISSUE TITLE
ISBN 10 with final x

### ISSUE THREAD

**Issue by AlexGrafic** [Fale/isbn#16]
Hi, i'm having some issues with the isbn's with final char 'x'. Here you have an example: 887983634x .
Do you know any fix for this?

**Comment by AlexGrafic** [comment]
Never mind i found the fix. We need to convert che char to upperchase. Maybe a little fix on file Validation.php at the line 85 will fix this.
Before:
`85: if ($isbn[$i] === 'X') {`
After:
`85: if (strtoupper($isbn[$i]) === 'X') {`

**Comment by Fale** [comment]
Thanks
